name: Deploy to Windows Prod

on:
    pull_request:
        types: [closed]
        branches:
            - main

jobs:
    windows-deploy:
        runs-on: ubuntu-latest
        env:
                  DB_HOST: ${{ secrets.PROD_DB_HOST }}
                  DB_PW: ${{ secrets.PROD_DB_PW}}
                  DB_USER: ${{ secrets.PROD_DB_USER }}
                  DB_NAME: ${{ secrets.PROD_DB_NAME }}
                  TWILIO_ACCOUNT_SID : ${{secrets.TWILIO_ACCOUNT_SID}}
                  TWILIO_AUTH_TOKEN1 : ${{secrets.TWILIO_AUTH_TOKEN2}}
                  TWILIO_AUTH_TOKEN2 :  ${{secrets.TWILIO_AUTH_TOKEN2}}
                  TWILIO_NUMBER : ${{secrets.TWILIO_NUMBER}}
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: main
            - uses: actions/setup-node@v1
            - run: |
                    touch .env
                    echo db_host="$DB_HOST" >> .env
                    echo db_pw="$DB_PW" >> .env
                    echo db_user="$DB_USER" >> .env
                    echo db_name="$DB_NAME" >> .env
                    echo twilio_account_sid="$TWILIO_ACCOUNT_SID" >> .env
                    echo twilio_auth_token1="$TWILIO_AUTH_TOKEN1" >> .env
                    echo twilio_auth_token2="$TWILIO_AUTH_TOKEN2" >> .env
                    echo twilio_number="$TWILIO_NUMBER" >> .env

            - run: npm install
            - run: npm run build
            - run: npm run bundle

            - name: Copy folder content recursively to remote
              uses: garygrossgarten/github-action-scp@release
              with:
                  local: dist/
                  remote: c:/Apache24/htdocs
                  recursive : true
                  host: 'tutorscheduling.oc.edu'
                  username: 'david.north'
                  privateKey: ${{ secrets.PROD_WIN_SERVER_SSH_KEY  }}

